### ISSUE TITLE
createa an association between two traces

### ISSUE THREAD

**Issue by RaduBerinde** [lightstep/lightstep-tracer-go#43]
We are looking for a way to associate two different traces so that they show as related to each other in the interface. Our usecase is: each transaction is a trace and has a bunch of spans. Sometimes transaction A conflicts with something that some other transaction B did. If are looking at A's spans, we want to be able to "jump" to B's spans. Currently it it very hard to identify transaction B and its spans.

One possible way to do that through the opentracing API would be to create a `Span` that derives from both traces - `StartSpan("conflict", FollowsFrom(ctxA), FollowsFrom(ctxB))`. Unofrtunately the basictracer-go code ignores everything but the first reference: https://github.com/opentracing/basictracer-go/blob/c7c0202a8a77f658aeb2193a27b6c0cfcc821038/tracer.go#L159

We could try to extend basictracer-go to support multiple references if lightstep would be able to handle them.

**Comment by RaduBerinde** [comment]
CC @tschottdorf @andreimatei

**Comment by bensigelman** [comment]
@RaduBerinde ACK

This is something I'd love to implement. There are a few issues here...

1. As you observed, BasicTracer doesn't do the right thing with N>1 references which is basically a bug.
1. Even if it did the right thing, the LightStep Frontend doesn't do anything special with multiple parents [yet]...
1. ... and most importantly, I don't think of these sorts of inter-trace references as being "multiple parents"; it's more like a pointer, and IMO deserves its own reference type at the OT layer.

Since you all actually have a legit production use case (yay), I would suggest opening an issue at https://github.com/opentracing/opentracing.github.io/issues describing the semantics you need. We can then go forward and talk about what that reference type should be (in a language-neutral way), then finally figure out how to represent it in the Go/etc APIs.

(PS: I think it's reasonable to add a pointer to another trace during the lifetime of a Span, not just at `StartSpan` time... so maybe it would make sense to have something like `log.Reference(...)` a la https://github.com/opentracing/opentracing-go/pull/108)

**Comment by RaduBerinde** [comment]
Thanks, filed https://github.com/opentracing/opentracing.github.io/issues/119

**Comment by bensigelman** [comment]
Thanks! I will close this as the real issue here (IMO) is the OT one. The larger feature request for LightStep is/was already on our radar and probably doesn't belong in the Go client lib regardless.
