### ISSUE TITLE
add info to span title without expanding operation name?

### ISSUE THREAD

**Issue by RaduBerinde** [lightstep/lightstep-tracer-go#69]
We have some cases where the operation name for a span is too generic and we would like to include more information in the title. For traces with hundreds of spans, it is tedious to open up each span to see the events inside just to find which one is the one you need.

The downside of using a dynamic operation name in `StartSpan` is that dashboards are less useful, as we can't get statistics over all spans for that operation.

I was wondering, would it be possible to somehow get more information to display alongside the span title (like it currently shows the binary name), perhaps by setting a special tag in the span?

CC @dt

**Comment by tedsuo** [comment]
Hi @RaduBerinde, I'm closing this issue because it is not go-specific, and wouldn't work very well if it was lightstep-specific as libraries would not be able to use it (though that is a possibility). I definitely see some utility in this, and opened an issue here to gauge community interest: https://github.com/opentracing/specification/issues/75
