### ISSUE TITLE
change default behavior to use gRPC

### ISSUE THREAD

**Issue by djspoons** [lightstep/lightstep-tracer-go#83]
Not a difficult change, so the main thing would be to document the new behavior.

**Comment by tedsuo** [comment]
So there's one wrinkle with this: `Options.UseGRPC` is a boolean, as opposed to a *boolean, and there are a variety of ways users may be generating the Options object. This means there's no way to differentiate between "I didn't set this field" and "I explicitly set it to false".

The safest thing to do would be to remove `Options.UseGRPC` and replace it with `Options.UseThrift`. This will of course break compilation everyone currently using gRPC, and silently switch everyone using thrift by default over to gRPC. Not ideal - i'd rather break compilation for everyone who is switching, and leave the gRPC users alone. 

Since we can't have the compile error where I would like it, I propose we break no one and leave the `UseGRPC` flag present but mark it as deprecated.

**Comment by djspoons** [comment]
That reasoning (and the conclusion) make sense to me.

**Comment by tedsuo** [comment]
Cool, the PR is here btw, let me know when we want to pull it in: https://github.com/lightstep/lightstep-tracer-go/pull/84
